version: '3'

services:
  dosye:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ${DOSYE_UPLOADS_PATH}:/var/dosye/uploads
    command: flask run --host=0.0.0.0
